name: DocFX

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.fsi"
      - "**/*.fs"
      - "**/*.fsx"
      - "assets/**"
      - "docfx/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docfx:
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore projects
        run: |
          dotnet restore fsrubik --ignore-failed-sources
          dotnet restore fsrubik.sharp --ignore-failed-sources

      - name: Build projects
        run: |
          dotnet build fsrubik --no-restore --configuration Release --output bin
          dotnet build fsrubik.sharp --no-restore --configuration Release --output bin

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build DocFX
        run: docfx docfx/docfx.json

      - name: Upload DocFX
        uses: actions/upload-pages-artifact@v3
        with:
          path: docfx/_site

      - name: Deploy DocFX
        id: deployment
        uses: actions/deploy-pages@v4
