name: Examples

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.fsi"
      - "**/*.fs"
      - "**/*.fsx"
  workflow_dispatch:

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore projects
        run: |
          dotnet restore fsrubik --ignore-failed-sources
          dotnet restore fsrubik.sharp --ignore-failed-sources

      - name: Build projects
        run: |
          dotnet build fsrubik --no-restore --configuration Release
          dotnet build fsrubik.sharp --no-restore --configuration Release

      - name: Pack projects
        run: |
          dotnet pack fsrubik --no-build --configuration Release
          dotnet pack fsrubik.sharp --no-build --configuration Release

      - name: Run examples
        run: |
          for example in examples/*.fsx; do
            if [[ -f "$example" ]]; then
              dotnet fsi "$example"
            fi
          done
        env:
          CI: true
